version: '2'

services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '2290:6379'


  app:
    build:
      context: app
      dockerfile: Dockerfile

    volumes:
      - /home/beemax/PycharmProjects/Bot/app:/data